### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by GuillaumeFromage** [jesseward/discogs-oauth-example#5]
Hey, I don't wanna bother "disguising your code into mine", to make it look like I haven't stolen your code ; there is no mention of license on you code, would you mine making a copyright/license thing ?

Super thanks !

G

**Comment by jesseward** [comment]
@GuillaumeFromage thanks for the feedback. I have added MIT license under https://github.com/jesseward/discogs-oauth-example/commit/8284be9bb977e429bc5d4174115c054a55364c9e
